name: Build, Push, Pull and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-flas-ci:latest .

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-flas-ci:latest

    - name: Pull the Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/python-flas-ci:latest

    - name: Stop and remove existing container (if running)
      run: |
        docker rm -f python-flas-ci || true

    - name: Run container on port 8080
      run: |
        docker run -d \
          --name python-flas-ci \
          -p 5000:5000 \
          ${{ secrets.DOCKER_USERNAME }}/python-flas-ci:latest
